spring:
  application:
  name: yeogiwa

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DB}?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO} # 'update' or 'create' in dev mode, 'validate' in op mode
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    open-in-view: false
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
      platform:

  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: ${BASE_URL}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: client_secret_post
          apple:
            client-id: ${APPLE_CLIENT_ID}
            key-id: ${APPLE_KEY_ID}
            team-id: ${APPLE_TEAM_ID}
            private-key: ${APPLE_PRIVATE_KEY}
            scope:
              - name
              - email
            redirect-uri: ${BASE_URL}/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-name: apple
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/oauth2/v2/authorize
            token-uri: https://appleid.apple.com/auth/oauth2/v2/token

openapi:
  festival-secret-key: ${OPENAPI_FESTIVAL_KEY}
  business-secret-key: ${OPENAPI_BUSINESS_KEY}

springdoc:
  swagger-ui:
    path: /api-docs
    enabled: true # 'true' in dev mode, 'false' in op mode
    #    oauth2RedirectUrl: /login/oauth2/code/kakao
    show-login-endpoint: true
    show-oauth2-endpoints: true
    enable-spring-security: true

logging.level:
  root: INFO
  org:
    springframework:
      security: DEBUG
    hibernate.SQL: DEBUG